# Generated by Django 4.2.5 on 2023-09-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
