# Generated by Django 4.2.5 on 2023-10-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_admin_profile_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
